// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/Muxly-Corp/muxly-shared/app"
	"github.com/Muxly-Corp/muxly-shared/queue"
	"github.com/google/wire"
	"github.com/Muxly-Corp/muxly-msg-subscriber/config"
	platform2 "github.com/Muxly-Corp/muxly-msg-subscriber/internal/domains/platform"
	"github.com/Muxly-Corp/muxly-msg-subscriber/internal/handlers"
	"github.com/Muxly-Corp/muxly-msg-subscriber/internal/middleware"
	"github.com/Muxly-Corp/muxly-msg-subscriber/internal/pkg/clients/muxly_backend"
	"github.com/Muxly-Corp/muxly-msg-subscriber/internal/repositories/messages"
	"github.com/Muxly-Corp/muxly-msg-subscriber/internal/services/platform"
)

// Injectors from wire.go:

func InitializeApp(infra *app.Infra) (*app.ServiceSetup, error) {
	healthCheckHandler := handlers.NewHealthCheckHandler()
	natsQueue := ProvideNATSQueue(infra)
	repository := messages.NewRepository(natsQueue)
	service := platform.NewService(repository)
	config := ProvideConfig(infra)
	subscriber := config.Subscriber
	subscribeToStreamerHandler := handlers.NewSubscribeToStreamerHandler(service, subscriber)
	serviceHandlerRouter := handlers.NewServiceHandlerRouter(healthCheckHandler, subscribeToStreamerHandler)
	muxlyBackend := config.MuxlyBackend
	client, err := muxly_backend.NewClient(muxlyBackend)
	if err != nil {
		return nil, err
	}
	auth := middleware.NewAuthMiddleware(client)
	serviceSetup := NewServiceSetup(serviceHandlerRouter, auth)
	return serviceSetup, nil
}

// wire.go:

var ConfigSet = wire.NewSet(ProvideConfig)

var QueueSet = wire.NewSet(
	ProvideNATSQueue, wire.Bind(new(queue.Queue), new(*queue.NATSQueue)),
)

var NATSRepoSet = wire.NewSet(messages.NewRepository)

var MuxlyBackendSet = wire.NewSet(wire.FieldsOf(new(*config.Config), "MuxlyBackend"), muxly_backend.NewClient, middleware.NewAuthMiddleware)

var PlatformServiceSet = wire.NewSet(platform.NewService, wire.Bind(new(platform2.Service), new(*platform.Service)))

var HandlerSet = wire.NewSet(wire.FieldsOf(new(*config.Config), "Subscriber"), handlers.NewHealthCheckHandler, handlers.NewSubscribeToStreamerHandler, handlers.NewServiceHandlerRouter)

var AppSet = wire.NewSet(NewServiceSetup)
